### ISSUE TITLE
Releasing a new version to Hackage

### ISSUE THREAD

**Issue by msakai** [jwaldmann/satchmo#8]
Thanks for merging my recent PRs for compatibility with recent GHC (#5, #6, #7).

I would appreciate it if you could upload a new version to the Hackage, enabling easy use with recent GHC.

**Comment by jwaldmann** [comment]
Sure. 

https://hackage.haskell.org/package/satchmo-2.9.9.4 

I checked that `cabal` install satchmo-2.9.9.4` works.

I am not seeing the docs on hackage. I don't know how to trigger a build there. Perhaps it's batched.

**Comment by msakai** [comment]
Thanks a lot!

Documentation appears to have been generated.
